services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: weddream_app
    restart: unless-stopped

    environment:
      APP_ENV: production
      APP_DEBUG: "false"

      DB_CONNECTION: mysql
      DB_HOST: mysql
      DB_PORT: ${DB_PORT}
      DB_DATABASE: ${DB_DATABASE}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}

    networks:
      - weddream

  nginx:
    image: nginx:alpine
    container_name: weddream_nginx
    restart: unless-stopped

    ports:
      - "81:80"

    depends_on:
      - app

    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro

    networks:
      - weddream


networks:
  weddream:
    driver: bridge
