server {
    listen 80;
    index index.php index.html;
    server_name localhost;
    root /var/www/html/public;

    # Redirection propre des URLs pour Laravel
    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    # Transmission des requêtes PHP à PHP-FPM
    location ~ \.php$ {
        fastcgi_pass app:9000; # "app" est le nom du service dans docker-compose
        fastcgi_index index.php;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param PATH_INFO $fastcgi_path_info;
    }
}
